fix bug
ElectronicBabylonianLiterature/ebl-frontend pull request #186
Opened 2021-11-30 16:48 UTC by yCobanoglu

2021-11-30 20:28 UTC, yCobanoglu commented
@jlaasonen it won't be possible to test this as it is impossible to create an annotation. Luis told me about this issue

2021-12-01 09:49 UTC, jlaasonen commented
> @jlaasonen it won't be possible to test this as it is impossible to create an annotation. Luis told me about this issue

How do you know it's fixed if it is not possible to test?

Please use descriptive PR names and commit messages. What bug is this?

2021-12-02 15:08 UTC, yCobanoglu commented
@jlaasonen tested it manually this PR stops from user making extremely small boxes which are impossible to delete

2021-12-03 07:02 UTC, jlaasonen requested changes
Add a proper title for the PR.

2021-12-03 07:02 UTC, jlaasonen commented on src/fragmentarium/ui/image-annotation/annotation-tool/FragmentAnnotation.tsx
> +        if (minSize >= 0.3) {
Extract method with a proper name to clarify what is going on. Avoid magic numbers.

2021-12-03 09:54 UTC, jlaasonen commented on src/fragmentarium/ui/image-annotation/annotation-tool/FragmentAnnotation.tsx
> +        if (minSize >= 0.3) {
If you extract a method it also becomes testable.

2021-12-06 08:32 UTC, jlaasonen commented on src/fragmentarium/ui/image-annotation/annotation-tool/FragmentAnnotation.test.tsx
> +  }
You can use [test.each](https://jestjs.io/docs/api#testeachtablename-fn-timeout) when there are multiple data for the same test.

2021-12-06 08:32 UTC, jlaasonen approved these changes

2021-12-06 12:49 UTC, merged