Display signs images
ElectronicBabylonianLiterature/ebl-frontend pull request #188
Opened 2021-12-05 16:13 UTC by yCobanoglu

2022-01-03 17:41 UTC, yCobanoglu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Display annotations in Signs interface](https://trello.com/c/C3BG2qRF/538-display-annotations-in-signs-interface)

2022-01-11 08:05 UTC, jlaasonen requested changes

2022-01-11 08:05 UTC, jlaasonen commented on src/signs/ui/display/__snapshots__/SignDisplay.test.tsx.snap
> +    <p>
Fix the test.

2022-01-11 08:05 UTC, jlaasonen commented on src/signs/ui/display/SignImages.tsx
> +          <Pagination>{items}</Pagination>
Wouldn't it be better to have to create all the pagination components in the same place? You could extract a component for the pagination.

2022-01-18 09:21 UTC, jlaasonen requested changes

2022-01-18 09:21 UTC, jlaasonen commented on src/signs/ui/display/SignImages.css
> +.SignImages__signImage {
Use lower case names for CSS classes: https://github.com/ElectronicBabylonianLiterature/ebl-frontend#htmlcss

If I remember correctly, we discussed this at some point.

2022-01-19 14:24 UTC, jlaasonen requested changes

2022-01-19 14:24 UTC, jlaasonen commented on src/signs/ui/display/SignImages.css
> +.signImages__signImage {
Change all letters to lower case.

2022-01-20 09:02 UTC, merged