Add DOIs
ElectronicBabylonianLiterature/ebl-frontend pull request #226
Opened 2022-03-16 14:18 UTC by khoidt

Add DOI to Text and display in Chapter, How to Cite. Ready for review.

2022-03-23 17:07 UTC, khoidt commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add DOIs to text](https://trello.com/c/tJKpwzeQ/460-add-dois-to-text)

2022-03-24 08:01 UTC, jlaasonen requested changes
👍 for fixing typos.

`textIdToDoiString` and `ChapterDisplay.doi` are missing tests. Diff test coverage is below the threshold.

2022-03-24 08:08 UTC, khoidt commented on src/corpus/domain/chapter.ts
> +    return this.textHasDoi ? textIdToDoiString(this.id.textId) : null
It was returning empty string at first, but this apparently breaks the RIS citation converter.

2022-03-24 08:12 UTC, khoidt commented on src/corpus/domain/text.ts
> +  readonly hasDoi?: string
Needs to be fixed, thanks for noticing.

2022-03-24 08:12 UTC, khoidt commented on src/corpus/domain/text.ts
> +  readonly hasDoi: string = ''
Needs to be fixed, thanks for noticing.

2022-03-24 08:50 UTC, jlaasonen commented on src/corpus/domain/chapter.ts
> +    return this.textHasDoi ? textIdToDoiString(this.id.textId) : null
According to the CSL-JSON schema, DOI is a `string`. If it does not exists it would be best to leave it out when creating `Cite`.

2022-03-24 09:45 UTC, khoidt commented on src/corpus/domain/chapter.ts
> +    return this.textHasDoi ? textIdToDoiString(this.id.textId) : null
I made the citation DOI a conditional property. The `doi()` function now returns and empty string when there's no DOI.

2022-03-24 10:51 UTC, jlaasonen approved these changes

2022-03-24 10:56 UTC, merged