Variant lines display
ElectronicBabylonianLiterature/ebl-frontend pull request #232
Opened 2022-03-30 12:55 UTC by khoidt

2022-03-30 12:56 UTC, khoidt commented
![](https://github.trello.services/images/mini-trello-icon.png) [Show variant lines](https://trello.com/c/WgkchWw7/569-show-variant-lines)

2022-04-22 07:30 UTC, jlaasonen requested changes

2022-04-22 07:30 UTC, jlaasonen commented on src/corpus/application/TextService.ts
> +                  )
Extract functions to make code more readable.

2022-04-22 07:30 UTC, jlaasonen commented on src/corpus/ui/ChapterViewLine.tsx
> +      {line.variants[variantNumber].intertext.length > 0 && (
You could add `hasIntertext` method to make the check simpler.

2022-04-22 07:30 UTC, jlaasonen commented on src/corpus/ui/ChapterViewLine.tsx
> +  variantNumber: number
The component only needs the variant. It would be better to pass it directly, or maybe just the intertext.

2022-04-22 07:30 UTC, jlaasonen commented on src/corpus/ui/ChapterViewLine.tsx
> +            key={variantId}
You can use the variant number as the key.

2022-04-22 07:30 UTC, jlaasonen commented on src/corpus/ui/ChapterViewLine.tsx
> +  const column = useMemo(
Use plural. There can be multiple columns.

2022-04-22 07:30 UTC, jlaasonen commented on src/corpus/ui/ChapterViewLine.tsx
> +          <td style={{ textAlign: 'right' }}>
Do not use inline styles.

If you prefer to use e.g. styled components, discuss with others and if agreed migrate all styles.

2022-04-22 07:30 UTC, jlaasonen commented on src/corpus/ui/ChapterViewLine.tsx
> +      line.variants[variantNumber].note && (
`line.variants[variantNumber]` is used a lot. Extract constant or prop.

2022-04-22 07:30 UTC, jlaasonen commented on src/corpus/ui/ChapterViewLine.tsx
> +          {variantNumber === 0 && scoreCaret}
Extract constant. E.g. `isPrimaryVariant`.

2022-04-22 07:30 UTC, jlaasonen commented on src/corpus/ui/Score.tsx
> +            )
Add a method to the line for getting the correct manuscripts.

The components should be as thin as possible. "Business" logic should go to models or services.

2022-04-22 07:30 UTC, jlaasonen commented on src/transliteration/ui/SubIndex.tsx
> +export function numberToUnicodeSubscript(
Move this to the application or domain. Do not export utility functions from components.

2022-04-22 11:36 UTC, jlaasonen requested changes

2022-04-22 11:36 UTC, jlaasonen commented on src/transliteration/application/SubIndex.tsx
>        ?.toString()
Move the component below back to `ui`.

2022-04-22 11:36 UTC, jlaasonen commented on src/transliteration/ui/DisplayToken.tsx
> +import SubIndex from '../application/SubIndex'
Use absolute paths.

2022-04-22 11:52 UTC, jlaasonen approved these changes

2022-04-22 11:56 UTC, merged