References info
ElectronicBabylonianLiterature/ebl-frontend pull request #42
Opened 2020-09-28 13:21 UTC by yCobanoglu

2020-09-28 13:23 UTC, yCobanoglu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Help bubble for Reference types](https://trello.com/c/uGBkwaeh/459-help-bubble-for-reference-types)

2020-09-30 07:36 UTC, jlaasonen requested changes

2020-09-30 07:36 UTC, jlaasonen commented on src/fragmentarium/ui/info/Info.tsx
> +        <code>D</code> = Discussion <br />
[Description list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl) might have been a more proper element choice.

2020-09-30 07:36 UTC, jlaasonen commented on src/fragmentarium/ui/info/Info.tsx
> +            }}
Avoid using inline styles. See: [style](https://reactjs.org/docs/dom-elements.html#style)

> Some examples in the documentation use `style` for convenience, **but using the `style` attribute as the primary means of styling elements is generally not recommended**. In most cases, [`className`](https://reactjs.org/docs/dom-elements.html#classname) should be used to reference classes defined in an external CSS stylesheet. `style` is most often used in React applications to add dynamically-computed styles at render time. See also [FAQ: Styling and CSS](https://reactjs.org/docs/faq-styling.html).

2020-10-02 08:56 UTC, jlaasonen approved these changes

2020-10-06 11:06 UTC, merged