fix test output for GenreSelection (type error map is undefined)
ElectronicBabylonianLiterature/ebl-frontend pull request #52
Opened 2020-11-19 16:18 UTC by yCobanoglu

I'm passing a props which gets used as state. Render method doesn't wait for state to be initialized before  executing.
It's fixed now.

2020-11-20 08:08 UTC, jlaasonen requested changes

2020-11-24 14:06 UTC, yCobanoglu commented on src/fragmentarium/ui/info/GenreSelection.tsx
> +          genres.genres.map((genreItem: Genre) => {
it was a problem with **factory boy**. I had defined genres there but wrongly (wrong type) it was left over from older days so thats why we got this error **factory boy** doesnt check types on initializing a fragment.

2020-11-25 09:15 UTC, jlaasonen requested changes

2020-11-25 09:15 UTC, jlaasonen commented on src/bibliography/ui/BibliographySearch.test.tsx
>    bibliographyService.search.mockReturnValueOnce(Promise.resolve(entries))
Remove duplicate configuration of the mock.

2020-12-03 12:45 UTC, yCobanoglu commented
in created a new PR (GenreSelection-bug-fix) which replaces this one.

2020-12-03 12:45 UTC, closed without merging